project:
  type: website
  output-dir: docs

website:
  title: "Learning Security - Use-Cases"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: cyber-security.qmd
        text: Cyber Security

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
